// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDgEZ70D5Qrl2CsxWyJOEniMzzZME4M1I',
    appId: '1:621754820904:web:9b9eda26a0fc212731481d',
    messagingSenderId: '621754820904',
    projectId: 'flutter-firbase-integration',
    authDomain: 'flutter-firbase-integration.firebaseapp.com',
    storageBucket: 'flutter-firbase-integration.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaDtJmlpnyBz1gdtX6QH9yr6uOgeNtdzI',
    appId: '1:621754820904:android:01bfe10fdbc9def331481d',
    messagingSenderId: '621754820904',
    projectId: 'flutter-firbase-integration',
    storageBucket: 'flutter-firbase-integration.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL3UcSxerZotxG5OuGm7hWUt3W5XAd2e4',
    appId: '1:621754820904:ios:3e41b01ebf3f6efb31481d',
    messagingSenderId: '621754820904',
    projectId: 'flutter-firbase-integration',
    storageBucket: 'flutter-firbase-integration.firebasestorage.app',
    iosBundleId: 'com.example.flutter6week25',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL3UcSxerZotxG5OuGm7hWUt3W5XAd2e4',
    appId: '1:621754820904:ios:3e41b01ebf3f6efb31481d',
    messagingSenderId: '621754820904',
    projectId: 'flutter-firbase-integration',
    storageBucket: 'flutter-firbase-integration.firebasestorage.app',
    iosBundleId: 'com.example.flutter6week25',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDgEZ70D5Qrl2CsxWyJOEniMzzZME4M1I',
    appId: '1:621754820904:web:6e0650019b2fc3c531481d',
    messagingSenderId: '621754820904',
    projectId: 'flutter-firbase-integration',
    authDomain: 'flutter-firbase-integration.firebaseapp.com',
    storageBucket: 'flutter-firbase-integration.firebasestorage.app',
  );

}